name: Build Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu, debian]
        args: [all]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: matrix.os != 'ubuntu' || matrix.args != 'normal'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./mainline/${{ matrix.os }}-${{ matrix.args }}/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v8
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nginx:${{ matrix.os }}-${{ matrix.args }}
